openapi: 3.0.0
info:
  title: MSA Support - Account
  description: |
    <sup>(ES)</sup> Microservicio de soporte que permite la consulta, creación, actualización, edición y eliminacion de cuentas. <br><br>
  version: 1.0.0
  contact:
    name: Arely Martinez
servers:
  - url: http://localhost:8080
    description: Development
tags:
  - name: Account
    description: Account Controller

paths:
  /support/accounts:
    get:
      tags:
        - Account
      summary: "⁽ᴱˢ⁾ Devuelve una lista de cuentas. \n⁽ᴱᴺ⁾ Retrieves a list of accounts.\n"
      operationId: GetAccountByFilter
      description: |
        ### Details:
        <sup>(ES)</sup> Permite realizar la consulta de cuentas.⠀<br>
        <sup>(EN)</sup> Allows consult accounts. <br><br>
        
        | Expected Result  | Path Parameter | Query Parameter                 |
        | ---------------- | ------------   | -----------------------------------|
        | Retrieves a list of accounts| - | -   |
        | Retrieves a account| - | accountNumber   |
        | Retrieves a account| - | customerId   |
      parameters:
        - name: accountNumber
          required: false
          in: query
          schema:
            type: string
            pattern: "^[0-9]+$"
          description: account number
        - name: customerId
          required: false
          in: query
          schema:
            type: string
            pattern: "^[0-9]+$"
          description: customer identification
      responses:
        "200":
          description: |
            <b>`OK`</b><br><br>
            <sup><i>(ES)</i></sup> Busqueda exitosa.
            <br><br>
            <sup><i>(EN)</i></sup> Successful search.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountByFilterResponse'
              examples:
                GetAccountByFilterResponseExample:
                  $ref: '#/components/examples/GetAccountByFilterResponseExample'
    post:
      tags:
        -  Account
      summary: "⁽ᴱˢ⁾ Guarda una cuenta. \n⁽ᴱᴺ⁾ Save an account.\n"
      operationId: PostAccount
      description: |-
        <sup>(ES)</sup> Permite realizar el guardado de cuentas.⠀<br>
        <sup>(EN)</sup> Allows you to save accounts. <br><br>
      requestBody:
        description: |-
          <sup><i>(ES)</i></sup> Cuenta a crear.
          <br><br>
          <sup><i>(EN)</i></sup> Account to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostAccountRequest'
            examples:
              PostAccountRequestExample:
                $ref: '#/components/examples/PostAccountRequestExample'
      responses:
        "201":
          description: |-
            <b>`Created`</b>
            <sup><i>(ES)</i></sup> Inserción exitosa.
            <br><br>
            <sup><i>(EN)</i></sup> Insertion successful.

  /support/accounts/{accountId}:
    get:
      tags:
        - Account
      summary: "⁽ᴱˢ⁾ Devuelve una cuenta. \n⁽ᴱᴺ⁾ Returns an account.\n"
      operationId: GetAccountById
      description: |
        ### Details:
        <sup>(ES)</sup> Permite realizar la consulta de una cuenta.⠀<br>
        <sup>(EN)</sup> Allows consult an account. <br><br>
        
        | Expected Result  | Path Parameter | Query Parameter                 |
        | ---------------- | ------------   | -----------------------------------|
        | Returns an account by id| accountId | -   |
      parameters:
        - name: accountId
          required: true
          in: path
          schema:
            type: string
            minLength: 1
            pattern: "^[0-9]+$"
          description: account identification
      responses:
        "200":
          description: |
            <b>`OK`</b><br><br>
            <sup><i>(ES)</i></sup> Busqueda exitosa.
            <br><br>
            <sup><i>(EN)</i></sup> Successful search.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountByIdResponse'
              examples:
                GetAccountByIdResponseExample:
                  $ref: '#/components/examples/GetAccountByIdResponseExample'
    put:
      tags:
        - Account
      summary: "⁽ᴱˢ⁾ Actualizar la cuenta. ⁽ᴱᴺ⁾ Update the account."
      description: |-
        <sup>(ES)</sup> Permite realizar el actualizado de la cuenta.⠀<br>
        <sup>(EN)</sup> Allows you to update your account. <br><br>
      operationId: PutAccount
      parameters:
        - name: accountId
          required: true
          in: path
          schema:
            type: string
            minLength: 1
            pattern: "^[0-9]+$"
          description: account identification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutAccountRequest'
            examples:
              PutAccountRequestExample:
                $ref: '#/components/examples/PutAccountRequestExample'
      responses:
        "200":
          description: |-
            <b>`OK`</b><br><br>
            <sup><i>(ES)</i></sup> Actualizacion exitosa.
            <br><br>
            <sup><i>(EN)</i></sup> Update successful.
    patch:
      tags:
        - Account
      summary: "⁽ᴱˢ⁾ Edita el estado de una cuenta. \n⁽ᴱᴺ⁾ Edit the status of an account.\n"
      operationId: PatchAccount
      parameters:
        - name: accountId
          required: true
          in: path
          schema:
            type: string
            minLength: 1
            pattern: "^[0-9]+$"
          description: account identification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchAccountRequest'
            examples:
              PatchAccountRequestExample:
                $ref: '#/components/examples/PatchAccountRequestExample'
      responses:
        "200":
          description: |-
            <b>`OK`</b><br><br>
            <sup><i>(ES)</i></sup> Actualizacion exitosa.
            <br><br>
            <sup><i>(EN)</i></sup> Update successful.
    delete:
      tags:
        - Account
      summary: "⁽ᴱˢ⁾ Elimina la cuenta. ⁽ᴱᴺ⁾ Delete the account."
      description: |-
        <sup>(ES)</sup> Permite realizar el eliminado de la cuente.⠀<br>
        <sup>(EN)</sup> Allows you to delete accounts. <br><br>
      operationId: DeleteAccount
      parameters:
        - name: accountId
          required: true
          in: path
          schema:
            type: string
            minLength: 1
            pattern: "^[0-9]+$"
          description: account identification
      responses:
        "200":
          description: |-
            <b>`OK`</b><br><br>
            <sup><i>(ES)</i></sup> Eliminación exitosa.
            <br><br>
            <sup><i>(EN)</i></sup> Deletion successful.            

components:
  schemas:
    GetAccountByFilterResponse:
      type: array
      description: |
        <sup><i>(ES)</i></sup>Respuesta con el listado de cuentas.
        <br><br>
        <sup><i>(EN)</i></sup>Responce with the list of accounts.
      items:
        $ref : "#/components/schemas/Account"
    GetAccountByIdResponse:
      type: object
      description: |
        <sup><i>(ES)</i></sup>Respuesta con la información de la cuenta.
        <br><br>
        <sup><i>(EN)</i></sup>Response with account information.
      allOf:
        - $ref:  "#/components/schemas/Account"
    PostAccountRequest:
      type: object
      description: |
        <sup><i>(ES)</i></sup>Información de la cuenta a guardar.
        <br><br>
        <sup><i>(EN)</i></sup>Account information to be saved.
      allOf:
        - $ref:  "#/components/schemas/PostAccount"
    PostAccount:
      type: object
      description: |
        <sup><i>(ES)</i></sup>Objeto con la información de una cuenta.
        <br><br>
        <sup><i>(EN)</i></sup>Object containing information about an account.
      properties:
        type:
          $ref: "#/components/schemas/Type"
        status:
          $ref: '#/components/schemas/Status'
        customerId:
          type: number
          description: |
            <sup><i>(ES)</i></sup>Identificación del cliente.
            <br><br>
            <sup><i>(EN)</i></sup>Customer identification.
          minLength: 1
          maxLength: 30
          pattern: "^[0-9]+$"
    PutAccountRequest:
      type: object
      description: |
        <sup><i>(ES)</i></sup>Información de la cuenta a actualizar.
        <br><br>
        <sup><i>(EN)</i></sup>Account information to update.
      allOf:
        - $ref:  "#/components/schemas/PutAccount"
    PatchAccountRequest:
      type: object
      description: |
        <sup><i>(ES)</i></sup>Información de la cuenta a actualizar.
        <br><br>
        <sup><i>(EN)</i></sup>Account information to update.
      allOf:
        - $ref:  "#/components/schemas/PatchAccount"
    Account:
      type: object
      description: |
        <sup><i>(ES)</i></sup>Objeto con la información de una cuenta.
        <br><br>
        <sup><i>(EN)</i></sup>Object containing information about an account.
      properties:
        accountId:
          type: string
          description: |
            <sup><i>(ES)</i></sup>Identificación de la cuenta.
            <br><br>
            <sup><i>(EN)</i></sup>Account identification.
          minLength: 1
          maxLength: 10
          pattern: "^[0-9]+$"
        accountNumber:
          type: string
          description: |
            <sup><i>(ES)</i></sup>Número de la cuenta.
            <br><br>
            <sup><i>(EN)</i></sup>Account number.
          minLength: 1
          maxLength: 10
          pattern: "^[0-9]+$"
        type:
          $ref: "#/components/schemas/Type"
        initialBalance:
          type: number
          description: |
            <sup><i>(ES)</i></sup>Saldo inicial de la cuenta.
            <br><br>
            <sup><i>(EN)</i></sup>Initial account balance.
        status:
          $ref: '#/components/schemas/Status'
        customerId:
          type: string
          description: |
            <sup><i>(ES)</i></sup>Identificación del cliente.
            <br><br>
            <sup><i>(EN)</i></sup>Customer identification.
          minLength: 1
          maxLength: 30
          pattern: "^[0-9]+$"
    Type:
      type: object
      properties:
        code:
          type: string
          description: |
            <sup><i>(ES)</i></sup>Código de tipo de cuenta.
            <br><br>
            <sup><i>(EN)</i></sup>Account type code.
          minLength: 1
        description:
          type: string
          description: |
            <sup><i>(ES)</i></sup>Descripción del tipo de cuenta.
            <br><br>
            <sup><i>(EN)</i></sup>Account Type description.
          minLength: 1
          maxLength: 45
          pattern: "^[a-zA-Z\\s]+$"
    Status:
      type: object
      description: |
        <sup><i>(ES)</i></sup>Estado de la cuenta.
        <br><br>
        <sup><i>(EN)</i></sup>Account status.
      properties:
        code:
          type: string
          description: status code
    PutAccount:
      type: object
      description: |
        <sup><i>(ES)</i></sup>Objeto con la información de una cuenta.
        <br><br>
        <sup><i>(EN)</i></sup>Object containing information about an account.
      properties:
        accountNumber:
          type: string
          description: |
            <sup><i>(ES)</i></sup>Número de la cuenta.
            <br><br>
            <sup><i>(EN)</i></sup>Account number.
          minLength: 1
          maxLength: 10
          pattern: "^[0-9]+$"
        type:
          $ref: "#/components/schemas/Type"
        initialBalance:
          type: number
          description: |
            <sup><i>(ES)</i></sup>Saldo inicial de la cuenta.
            <br><br>
            <sup><i>(EN)</i></sup>Initial account balance.
        status:
          $ref: '#/components/schemas/Status'
        customerId:
          type: number
          description: |
            <sup><i>(ES)</i></sup>Identificación del cliente.
            <br><br>
            <sup><i>(EN)</i></sup>Customer identification.
          minLength: 1
          maxLength: 30
          pattern: "^[0-9]+$"
    PatchAccount:
      type: object
      description: |
        <sup><i>(ES)</i></sup>Objeto con la información de una cuenta.
        <br><br>
        <sup><i>(EN)</i></sup>Object containing information about an account.
      properties:
        status:
          $ref: '#/components/schemas/Status'


  examples:
    GetAccountByFilterResponseExample:
      value:
        - accountId: '0358921080'
          accountNumber: '916999756'
          type:
            code: Ahorro
            description: esLrIhwdkslLjxmgxjIvUJSOyFBkgxReZFLLtLHiOxg
          initialBalance: 0
          status:
            code: string
          customerId: '327893875780748161755396843141'
        - accountId: '0358921080'
          accountNumber: '916999756'
          type:
            code: string
            description: esLrIhwdkslLjxmgxjIvUJSOyFBkgxReZFLLtLHiOxg
          initialBalance: 0
          status:
            code: string
          customerId: '327893875780748161755396843141'
    PostAccountRequestExample:
      value:
        type:
          code: C
          description: Corriente
        status:
          code: Enable
        customerId: 2

    GetAccountByIdResponseExample:
      value:
        accountId: '5124814641'
        accountNumber: '0626834818'
        type:
          code: CTE
          description: eNkzvMzYKvKDitSictJWJsxjlm oBznHPcy
        initialBalance: 200
        status:
          code: 'Activo'
        customerId: '978941375666779201730629821220'
    PutAccountRequestExample:
      value:
        accountNumber: '5577376954'
        type:
          code: A
          description: Ahorro
        initialBalance: 200
        status:
          code: 'Enable'
        customerId: 3
    PatchAccountRequestExample:
      value:
        status:
          code: "Disabled"


